### ISSUE TITLE
Blinking ui

### ISSUE THREAD

**Issue by p-lr** [SergKolo/udisks-indicator#3] opened 2016-10-09 12:17 UTC
Hi,

First of all, good job for this indicator!
I though observe blinks, like if the list of partition was refreshed every 5s. Maybe this is due to my autofs-mounted partitions.

**Comment by SergKolo** [comment] 2016-10-09 22:06
@peterLaurence the blinking menu has been an issue before and I hoped that it was fixed with caching the partition information, but apparently it wasn't. The likely cause of that is changes in the amount of disk usage:  the applications like browsers continuously store data on disk, so it's amount of used space changes all the time. The indicator is supposed to rebuild the menu each time, but i see now it's not practical due to continuous changes caused by other applications. I'll seek a way to update labels of partitions  without rebuilding whole menu.

I know that Ubuntu's Unity panel also from time to time issues ReSync signal, which updates the panel. If that's the cause, there's not much I can do.

**Comment by SergKolo** [comment] 2016-10-23 22:37
@peterLaurence  Hi there !  I've committed a few changes to the code, so now instead of rebuilding menu each time usage changes, it will only update label, so no more constantly flickering UI. It still may flicker if new device is  mounted though . The changes should be on their way to PPA soon, so give it 24 hours to be imported and then run apt-get update and apt-get upgrade. Let me know if there are any issues with the changes. Thanks !

**Closed as completed by SergKolo** 2016-10-23 22:37 UTC
